### ISSUE TITLE
Figure out how to get nicely & easily rendering tables in docs (.rst / Sphinx)

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#120]

**Comment by nathanesau** [comment]
Hello :smile:

YouTube notified me that a live stream was going on and from what I gathered, you are trying to bring J into the 21st century by re-writing some of the code-base in C++ 20. It sounds like a cool idea.

I created a fork and added a commit showing how to do tables in Sphinx (.rst) file. See [here for the code](https://github.com/nathanesau/jsource/commit/32b85611b401c9cc5ad3845346d3558c58a04554).

Result is shown below. No PR because it's just a proof of concept and doesn't contain any meaningful documentation.

![Screenshot_2021-02-06_21-55-16](https://user-images.githubusercontent.com/4649987/107135221-d453b100-68c6-11eb-96d0-260a898591ef.png)

**Comment by juntuu** [comment]
I think the emphasis was on "easily", i.e. manually aligning the table cells was not an option.

This would be solved with easy to use auto-formatter for the rst tables.

**Comment by nathanesau** [comment]
> I think the emphasis was on "easily", i.e. manually aligning the table cells was not an option.
> 
> This would be solved with easy to use auto-formatter for the rst tables.

Based on your suggestion that we want to be able to write tables "easily", i.e. not manually aligning table cells, I have provided a way to write markdown tables in the RST files. This should make it very easy to add tables to the docs.

https://github.com/codereport/jsource/pull/129
