### ISSUE TITLE
Parallelize unit tests

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#2]
Currently takes:
```
Total Test time (real) = 291.91 sec
```
on one core.
Fix me.

**Comment by zhihaoy** [comment]
You can run the unit tests under the `build` directory with the `ctest` tool instead, for example, `ctest -C Release` (`-C` stands for "build config", `Debug` or `Release`), where you can add `-j` to the command-line. However, you may see some tests failing if you run them in parallel. That is because some tests (under the `test` directory, grep for `'~temp'` to find out) are opening temporary files under the same name. You may fix this by naming those files differently.

**Comment by codereport** [comment]
@zhihaoy Awesome, I will give this a shot on the next stream! :pray: thanks

**Comment by codereport** [comment]
This works now.
